---
- name: Install and configure Nginx on Amazon Linux 2023 EC2 instances
  hosts: webservers
  become: yes

  tasks:
    - name: Update all system packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install Nginx package
      dnf:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled at boot
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy a basic Nginx index.html page
      copy:
        content: "<html><body><h1>Nginx is working on EC2!</h1></body></html>"
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'
